SDE_INSTALL : "/home/gys/bf-sde-9.13.2/install"
SDE : "/home/gys/bf-sde-9.13.2"
PYTHON_VERSION: "python3.10"

SOUTHBOUND_SERVER_IP_1 :  '127.0.0.1'
SOUTHBOUND_SERVER_IP_2 :  '192.100.11.162'
SOUTHBOUND_SERVER_IP_3 :  '192.100.11.163'
SOUTHBOUND_SERVER_IP_4 :  '192.100.11.164'
SOUTHBOUND_SERVER_IP_5 :  '192.100.11.165'
SOUTHBOUND_SERVER_IP_6 :  '192.100.11.166'
SOUTHBOUND_SERVER_IP_7 :  '192.100.11.167'
SOUTHBOUND_SERVER_IP_8 :  '192.100.11.168'
SOUTHBOUND_SERVER_IP_9 :  '192.100.11.172'
SOUTHBOUND_SERVER_IP_10 : '192.100.11.173'
SOUTHBOUND_SERVER_IP_11 : '192.100.11.174'
SOUTHBOUND_SERVER_IP_12 : '192.100.11.175'
SOUTHBOUND_SERVER_IP_13 : '192.100.11.169'
SOUTHBOUND_SERVER_IP_14 : '192.100.11.176'
SOUTHBOUND_SERVER_IP_15 : '192.100.11.177'
SOUTHBOUND_SERVER_IP_16 : '192.100.11.170'
SOUTHBOUND_SERVER_IP_17 : '192.100.11.171'

SOUTHBOUND_SERVER_PORT : '11451'
P4_NAME : 'flep_process'

DB_PORT : '3306'
DB_NAME : 'flep_db'
DB_USER : 'root'
DB_PASSWORD : '123456'

#main switch
LOCAL_LABEL_1 : '0x2501'
# 1/0，2/0，3/0，4/0，5/0，6/0，7/0，8/0，9/0
PORT_LIST_1 :
    1 : 1
    2 : 2
    3 : 3
    4 : 4
    5 : 5
    6 : 6
    7 : 7
    8 : 8
    9 : 9
PORT_LIMIT_1 :
    1: "40G"
    2: "100G"
    3: "100G"
    4: "100G"
    5: "100G"
    6: "100G"
    7: "40G"
    8: "100G"
    9: "40G"
# 1/0，2/0，3/0，4/0，5/0，6/0，7/0，8/0
LOCAL_LABEL_2 : '0x2502'
PORT_LIST_2 :
    140 : 1
    132 : 2
    156 : 3
    148 : 4
    172 : 5
    164 : 6
    188 : 7
    180 : 8
PORT_LIMIT_2 :
    140: "100G"
    132: "40G"
    156: "40G"
    148: "100G"
    172: "100G"
    164: "100G"
    188: "100G"
    180: "100G"

# 1/0，2/0，3/0，4/0，5/0，6/0，7/0，8/0
LOCAL_LABEL_3 : '0x2503'
PORT_LIST_3 :
    140 : 1
    132 : 2
    156 : 3
    148 : 4
    172 : 5
    164 : 6
    188 : 7
    180 : 8
PORT_LIMIT_3 :
    140: "100G"
    132: "100G"
    156: "100G"
    148: "100G"
    172: "100G"
    164: "40G"
    188: "100G"
    180: "100G"

# 1/0，2/0，3/0，4/0，5/0，6/0，7/0
LOCAL_LABEL_4 : '0x2504'
PORT_LIST_4 :
    140 : 1
    132 : 2
    156 : 3
    148 : 4
    172 : 5
    164 : 6
    188 : 7
PORT_LIMIT_4 :
    140: "100G"
    132: "100G"
    156: "100G"
    148: "100G"
    172: "100G"
    164: "100G"
    188: "40G"

# 1/0，2/0，3/0，4/0，5/0，6/0
LOCAL_LABEL_5 : '0x2505'
PORT_LIST_5 :
    140 : 1
    132 : 2
    156 : 3
    148 : 4
    172 : 5
    164 : 6
PORT_LIMIT_5 :
    140: "40G"
    132: "100G"
    156: "100G"
    148: "100G"
    172: "100G"
    164: "100G"
# 1/0，2/0，3/0，4/0
LOCAL_LABEL_6 : '0x2506'
PORT_LIST_6 :
    140 : 1
    132 : 2
    156 : 3
    148 : 4
PORT_LIMIT_6 :
    140: "100G"
    132: "100G"
    156: "100G"
    148: "100G"

# 1/0，2/0
LOCAL_LABEL_7 : '0x2507'
PORT_LIST_7 :
    140 : 1
    132 : 2
PORT_LIMIT_7 :
    140: "100G"
    132: "100G"

# 1/0，2/0，3/0，4/0 
LOCAL_LABEL_8 : '0x2508'
PORT_LIST_8 :
    140 : 1
    132 : 2
    156 : 3
    148 : 4
PORT_LIMIT_8 :
    140: "100G"
    132: "100G"
    156: "100G"
    148: "100G"

# 1/0，2/0  fz
LOCAL_LABEL_9 : '0x2509'
PORT_LIST_9 :
    140 : 1
    132 : 2
PORT_LIMIT_9 :
    140: "40G"
    132: "40G"

# 1/0，2/0，33/0 fz（需要加IP）
LOCAL_LABEL_10 : '0x250A'
PORT_LIST_10 :
    140 : 1
    132 : 2
    64  : 3
PORT_LIMIT_10 :
    140: "100G"
    132: "100G"
    64 : "10G"

# 1/0，2/0，33/0  fz（需要加IP）
LOCAL_LABEL_11 : '0x250B'
PORT_LIST_11 :
    140 : 1
    132 : 2
    64  : 3
PORT_LIMIT_11 :
    140: "40G"
    132: "40G"
    64 : "10G"

# 1/0，2/0 fz
LOCAL_LABEL_12 : '0x250C'
PORT_LIST_12 :
    140 : 1
    132 : 2
PORT_LIMIT_12 :
    140: "40G"
    132: "40G"

# 1/0，2/0
LOCAL_LABEL_13 : '0x250D'
PORT_LIST_13 :
    140 : 1
    132 : 2
PORT_LIMIT_13 :
    140: "100G"
    132: "100G"

# 1/0 fz
LOCAL_LABEL_14 : '0x250E'
PORT_LIST_14 :
    140 : 1
PORT_LIMIT_14 :
    140: "40G"

# 1/0 fz
LOCAL_LABEL_15 : '0x250F'
PORT_LIST_15 :
    140 : 1
PORT_LIMIT_15 :
    140: "40G"

# 1/0，2/0
LOCAL_LABEL_16 : '0x2510'
PORT_LIST_16 :
    140 : 1
    132 : 2
PORT_LIMIT_16 :
    140: "100G"
    132: "100G"

# 1/0，2/0
LOCAL_LABEL_17 : '0x2511'
PORT_LIST_17 :
    140 : 1
    132 : 2
PORT_LIMIT_17 :
    140: "100G"
    132: "100G"