SDE : "/home/ruijie/onl-bf-sde"
SDE_INSTALL : "/home/ruijie/onl-bf-sde/install"
PYTHON_VERSION: "python3.9"

SOUTHBOUND_SERVER_IP_1 :  '10.0.0.11'
SOUTHBOUND_SERVER_IP_2 :  '10.0.0.12'
SOUTHBOUND_SERVER_IP_3 :  '10.0.0.13'


SOUTHBOUND_SERVER_PORT : '11451'
P4_NAME : 'flep_encap'

DB_PORT : '3306'
DB_NAME : 'flep_encap_db'
DB_USER : 'root'
DB_PASSWORD : '123456'

#main switch
LOCAL_LABEL_1 : '0x2501'
# 1/0, 33/0
PORT_LIST_1 :
    128 : 1
    64 : 33
    
PORT_LIMIT_1 :
    1: "100G"
    33: "10G"

# 1/0ï¼Œ2/0
LOCAL_LABEL_2 : '0x2502'
PORT_LIST_2 :
    132 : 1
    140 : 2
PORT_LIMIT_2 :
    1: "100G"
    2: "100G"
# 1/0, 33/0
LOCAL_LABEL_3 : '0x2503'
PORT_LIST_3 :
    132 : 1
    64 : 33
PORT_LIMIT_3 :
    1: "100G"
    33: "10G"
